openapi: "3.0.3"

info:
  title: "Sample API"
  version: "1.0.0"

servers:
  - url: 	https://dummy.restapiexample.com/api/v1
    description: Optional server description,

paths:
  "/employees":
    get:
      summary: "メッセージ取得"
      description: "メッセージを取得します"
      responses:
        "200":
          description: "Success operation"
          content:
            application/json:
              schema:
                type: string
                example: "Hello World!!"